# Generated by Django 4.2.11 on 2024-05-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='productvariant',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
