# Generated by Django 4.2.11 on 2024-08-31 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_orderstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
