# Generated by Django 4.2.11 on 2024-09-29 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoppingbagitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='shoppingbagitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='shoppingbagitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shoppingbagitem',
            name='variant',
        ),
        migrations.DeleteModel(
            name='ShoppingBag',
        ),
        migrations.DeleteModel(
            name='ShoppingBagItem',
        ),
    ]
