# Generated by Django 4.2.11 on 2024-09-22 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_wishlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'size')},
        ),
    ]
